### ISSUE TITLE
DUPLICATE of #16: Variable handling incompatible with vagrant 1.5

### ISSUE THREAD

**Issue by joshuata** [kusnier/vagrant-persistent-storage#17]
After updating vagrant to 1.5, performing a `vagrant up` results in the following:

```
/Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/plugin/v2/config.rb:73:in `method_missing': undefined local variable or method `mount_point' for #<VagrantPlugins::PersistentStorage::Config:0x000001012d5b70> (NameError)
    from /Users/*****/.vagrant.d/gems/gems/vagrant-persistent-storage-0.0.10/lib/vagrant-persistent-storage/config.rb:118:in `validate'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/config/v2/root.rb:68:in `block in validate'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/config/v2/root.rb:64:in `each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/config/v2/root.rb:64:in `validate'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/action/builtin/config_validate.rb:15:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/action/builtin/call.rb:57:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/action/builder.rb:116:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/action/runner.rb:69:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/action/runner.rb:69:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/machine.rb:157:in `action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/batch_action.rb:72:in `block (2 levels) in run'
```
